language: shell
os: windows
env:
  global:
    - NODEJS_VERSION: 11.9.0
before_install:
  - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
  - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/nodejs.sh
  - set
script:
  - node_modules/.bin/eslint .
  - node_modules/.bin/stylelint "**/*.css"
  - node_modules/.bin/wdio
