language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
sudo: required
cache:
  directories:
    - node_modules
addons:
  artifacts:
    paths:
      - ./errorShots/
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    s3_region: "ap-southeast-2"
  chrome: "stable"
  firefox: "latest"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm config set spin false; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$HOME/.yarn/bin:$PATH"; fi
script:
  - yarn lint
  - node_modules/.bin/stylelint "**/*.less" --custom-syntax postcss-less
  - yarn e2e
