language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "8"
sudo: required
cache:
  directories:
    - node_modules
addons:
  artifacts:
    debug: true
    paths:
      - ./errorShots/
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    s3_region: "ap-southeast-2"
  chrome: "stable"
  # firefox: "latest"
  java: "8"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm config set spin false; fi
script:
  - node_modules/.bin/eslint .
  - node_modules/.bin/stylelint "**/*.css"
  - node_modules/.bin/wdio
