language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
sudo: required
cache:
  directories:
    - node_modules
addons:
  chrome: "stable"
script:
  - yarn lint
  - node_modules/.bin/stylelint "**/*.less" --custom-syntax postcss-less
  - yarn e2e
