language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
sudo: required
cache:
  directories:
    - node_modules
addons:
  artefacts: "true"
  paths:
  - $(ls ./errorShots/*.png | tr "\n" ":")
  chrome: "stable"
  firefox: "62.0.3"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm config set spin false; fi
script:
  - node_modules/.bin/eslint .
  - node_modules/.bin/stylelint "**/*.css"
  - node_modules/.bin/wdio
