language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
sudo: required
cache:
  directories:
    - node_modules
addons:
  chrome: "stable"
  firefox: "latest"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
script:
  - node_modules/.bin/eslint .
  - node_modules/.bin/stylelint "**/*.css"
  - node_modules/.bin/wdio
