language: shell
os: windows
env:
  global:
    - NODEJS_VERSION: 11.9.0
before_install:
  - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
  - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/nodejs.sh
  - set
  - choco install python googlechrome firefox
script:
  - export NVS_HOME=$ProgramData/nvs
  - git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME
  - source $NVS_HOME/nvs.sh
  - nvs --version
  - nvs add $NODEJS_VERSION && nvs use $NODEJS_VERSION
  - npm i
  - node_modules/.bin/eslint .
  - node_modules/.bin/stylelint "**/*.css"
  - node_modules/.bin/wdio
