# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Cache
      uses: actions/cache@v2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: node_modules
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        yarn
        yarn lint
        node_modules/.bin/stylelint "**/*.less" --custom-syntax postcss-less
        yarn e2e
